### ISSUE TITLE
Line breaks support for comments

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#389]
Comments must support line breaks. Current implementation does not support line breaks.

**Comment by indeyets** [comment]
Done.

**Comment by guiltypet** [comment]
Issue still exist. Comments not supporting line break. Verified on Windows Pro 7/Chrome 49.

**Comment by xekc** [comment]
@ihork I don't think this is deployed yet, @indeyets ?

**Comment by indeyets** [comment]
Not deployed. My issue.

**Comment by guiltypet** [comment]
Fixed. Verified on Win 7/Chrome 50, iPhone 6 /iOS 9.3.1
Please see the Screenshot below.
